name: cacttus_db

services:
  pg:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker_dev
      - POSTGRES_PASSWORD=docker_dev
      - POSTGRES_DB=cacttus

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080